import { AiOutlineHome } from "react-icons/ai";
import { MdOutlineMail } from "react-icons/md";
import { RiLock2Line } from "react-icons/ri";
import { FcCancel } from "react-icons/fc";
import { FiRefreshCcw } from "react-icons/fi";
import { GiClick } from "react-icons/gi";
import { SlArrowRight } from "react-icons/sl";
import { SlArrowLeft } from "react-icons/sl";
import { SlArrowUp } from "react-icons/sl";
import { SlArrowDown } from "react-icons/sl";
import { MdKeyboardArrowDown } from "react-icons/md";
import { AiOutlineArrowDown } from "react-icons/ai";
import { FaSearch } from "react-icons/fa";
import { HiOutlineLockClosed } from "react-icons/hi";
import { FaEye } from "react-icons/fa";
import { MdHelp } from "react-icons/md";

export const AiOutlineHomeIcon = () => <AiOutlineHome />;
export const MdOutlineMailIcon = () => <MdOutlineMail />;
export const RiLock2LineIcon = () => <RiLock2Line />;
export const FcCancelIcon = () => <FcCancel />;
export const FiRefreshCcwIcon = () => <FiRefreshCcw />;
export const GiClickIcon = () => <GiClick />;
export const SlArrowRightIcon = () => <SlArrowRight />;
export const SlArrowLeftIcon = () => <SlArrowLeft />;
export const SlArrowUpIcon = () => <SlArrowUp />;
export const SlArrowDownIcon = () => <SlArrowDown />;
export const MdKeyboardArrowDownIcon = () => <MdKeyboardArrowDown />;
export const AiOutlineArrowDownIcon = () => <AiOutlineArrowDown />;
export const FaSearchIcon = () => <FaSearch />;
export const HiOutlineLockClosedIcon = () => <HiOutlineLockClosed />;
export const FaEyeIcon = () => <FaEye />;
export const MdHelpIcon = () => <MdHelp />;
